### ISSUE TITLE
Symlinking requires administrative privileges in Windows

### ISSUE THREAD

**Issue by juanevp** [shyiko/tsdm#1]
When executing `tsdm rewire` from the Windows shell it fails with this error: 

```
Error: EPERM: operation not permitted, symlink 'C:\...\node_modules\immutable' -> 'C:\...\typings\immutable'
    at Error (native)
```

When it is executed from a shell with elevated privileges it succeeds. From the comments in the code symlinking is there to accommodate WebStorm 11. Perhaps this strategy should be optional (behind some switch) and by default it should do something like copying the relevant files to the typings directory or just pointing them from tsd.d.ts to their original locations.

**Comment by shyiko** [comment]
Wow. Thank you for letting me know. I'll look into it.

**Comment by shyiko** [comment]
Symlinking is turned off by default but can be enabled if necessary as shown [here](https://github.com/shyiko/tsdm/commit/bd736c63ade4b229b509d55863201fe0eee5acc4#diff-faa503f61f8addeb603095cc2f40c82eR50). Verified on Windows 10 Build 10240.

**Comment by shyiko** [comment]
@juanevp Thanks again :beers:
